version: '3.8'
services:
  driver:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"

  crawler:
    build:
      context: ./app
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    depends_on:
      - driver
